LogosBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.LogosBucket.name}

LogosBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref LogosBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.LogosBucket.name}/*
