HotelsInfoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: HotelsInfoTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: code
        AttributeType: S
      - AttributeName: type
        AttributeType: S
    KeySchema:
      - AttributeName: type
        KeyType: HASH
      - AttributeName: code
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

    StreamSpecification:
      StreamViewType: NEW_IMAGE
